name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

permissions: {}
jobs:
  run:
    permissions:
      pull-requests: write #  to comment on and close pull-request

    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Thank you for your pull request. However, you have submitted this PR on the Illuminate organization which is a read-only sub split of `laravel/framework`. Please submit your PR on the https://github.com/laravel/framework repository.<br><br>Thanks!"
